/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busticket;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;
import java.sql.*;


/**
 *
 * @author pravinewa
 */
public class AccountSetting extends javax.swing.JFrame {
    static int sidebar = 0;
    static int mousepX, mousepY;  
        static int ivalid = 0, pvalid = 0, snvalid = 0, emailvalid = 0, contactnumbervalid = 0, addressvalid = 0;

    /**
     * Creates new form OpenPanel
     */
    public AccountSetting() {
        initComponents();
    }
    private void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        shiftButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        fareCalculatorButton = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();
        showButton = new javax.swing.JButton();
        lineSeparator3 = new javax.swing.JSeparator();
        lineSeparator2 = new javax.swing.JSeparator();
        lineSeparator1 = new javax.swing.JSeparator();
        lineSeparator4 = new javax.swing.JSeparator();
        lineSeparator5 = new javax.swing.JSeparator();
        signOutLabel = new javax.swing.JLabel();
        HideLabel = new javax.swing.JLabel();
        fareCalculatorLabel = new javax.swing.JLabel();
        busManagementLabel = new javax.swing.JLabel();
        lineSeparator6 = new javax.swing.JSeparator();
        newTicketButton = new javax.swing.JButton();
        reservationLabel = new javax.swing.JLabel();
        adminButton = new javax.swing.JButton();
        lineSeparator7 = new javax.swing.JSeparator();
        adminPanelLabel = new javax.swing.JLabel();
        ticketButton = new javax.swing.JButton();
        lineSeparator8 = new javax.swing.JSeparator();
        ticketLabel = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        minimizeButton = new javax.swing.JButton();
        showUserLabel = new javax.swing.JLabel();
        showUserLabel1 = new javax.swing.JLabel();
        staffIdLabel = new javax.swing.JLabel();
        staffNameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        contactnoLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        shiftLabel = new javax.swing.JLabel();
        genderLabel4 = new javax.swing.JLabel();
        genderLabel5 = new javax.swing.JLabel();
        genderLabel6 = new javax.swing.JLabel();
        genderLabel7 = new javax.swing.JLabel();
        genderLabel8 = new javax.swing.JLabel();
        genderLabel9 = new javax.swing.JLabel();
        genderLabel10 = new javax.swing.JLabel();
        genderLabel11 = new javax.swing.JLabel();
        staffIdSeperator = new javax.swing.JSeparator();
        staffNameSeparator = new javax.swing.JSeparator();
        passwordField = new javax.swing.JPasswordField();
        passwordSeparator = new javax.swing.JSeparator();
        emailTextField = new javax.swing.JTextField();
        emailSeparator = new javax.swing.JSeparator();
        contactNumberTextField = new javax.swing.JTextField();
        contactNumberSeparator = new javax.swing.JSeparator();
        addressTextField = new javax.swing.JTextField();
        addressSeparator = new javax.swing.JSeparator();
        passwordLabel1 = new javax.swing.JLabel();
        genderLabel12 = new javax.swing.JLabel();
        passwordField1 = new javax.swing.JPasswordField();
        passwordSeparator1 = new javax.swing.JSeparator();
        showpass = new javax.swing.JCheckBox();
        showpass1 = new javax.swing.JCheckBox();
        addButton1 = new javax.swing.JButton();
        showValidationOfStaffId = new javax.swing.JLabel();
        showValidationOfStaffName = new javax.swing.JLabel();
        showValidationOfPassword = new javax.swing.JLabel();
        showValidationOfEmail = new javax.swing.JLabel();
        showValidationOfContactNumber = new javax.swing.JLabel();
        showValidationOfAddress = new javax.swing.JLabel();
        showValidationOfPassword1 = new javax.swing.JLabel();
        staffIdLabel9 = new javax.swing.JLabel();
        staffIdLabel10 = new javax.swing.JLabel();
        staffIdLabel11 = new javax.swing.JLabel();
        staffNameSeparator1 = new javax.swing.JSeparator();
        staffIdLabel12 = new javax.swing.JLabel();
        staffNameSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        mainPanel.setPreferredSize(new java.awt.Dimension(1070, 530));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarPanel.setBackground(new java.awt.Color(1, 50, 67));

        addButton.setBackground(new java.awt.Color(1, 50, 67));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/icons8-calendar-416.png"))); // NOI18N
        addButton.setBorder(null);
        addButton.setBorderPainted(false);
        addButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addButton.setFocusPainted(false);
        addButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        fareCalculatorButton.setBackground(new java.awt.Color(1, 50, 67));
        fareCalculatorButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fareCalculatorButton.setForeground(new java.awt.Color(255, 255, 255));
        fareCalculatorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/icons8-calculator-500.png"))); // NOI18N
        fareCalculatorButton.setBorder(null);
        fareCalculatorButton.setBorderPainted(false);
        fareCalculatorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fareCalculatorButton.setFocusPainted(false);
        fareCalculatorButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        fareCalculatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fareCalculatorButtonActionPerformed(evt);
            }
        });

        signOutButton.setBackground(new java.awt.Color(1, 50, 67));
        signOutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signOutButton.setForeground(new java.awt.Color(255, 255, 255));
        signOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/sign-out.png"))); // NOI18N
        signOutButton.setBorder(null);
        signOutButton.setBorderPainted(false);
        signOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOutButton.setFocusPainted(false);
        signOutButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });

        showButton.setBackground(new java.awt.Color(1, 50, 67));
        showButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showButton.setForeground(new java.awt.Color(255, 255, 255));
        showButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/menu.png"))); // NOI18N
        showButton.setBorder(null);
        showButton.setBorderPainted(false);
        showButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showButton.setFocusPainted(false);
        showButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        signOutLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signOutLabel.setForeground(new java.awt.Color(255, 255, 255));
        signOutLabel.setText("Sign Out");
        signOutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signOutLabelMouseClicked(evt);
            }
        });

        HideLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HideLabel.setForeground(new java.awt.Color(255, 255, 255));
        HideLabel.setText("Hide");
        HideLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HideLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HideLabelMouseClicked(evt);
            }
        });

        fareCalculatorLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fareCalculatorLabel.setForeground(new java.awt.Color(255, 255, 255));
        fareCalculatorLabel.setText("Fare Calculator");
        fareCalculatorLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fareCalculatorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fareCalculatorLabelMouseClicked(evt);
            }
        });

        busManagementLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        busManagementLabel.setForeground(new java.awt.Color(255, 255, 255));
        busManagementLabel.setText("Bus Management");
        busManagementLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        busManagementLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busManagementLabelMouseClicked(evt);
            }
        });

        newTicketButton.setBackground(new java.awt.Color(1, 50, 67));
        newTicketButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newTicketButton.setForeground(new java.awt.Color(255, 255, 255));
        newTicketButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/icons8-new-ticket-416.png"))); // NOI18N
        newTicketButton.setBorder(null);
        newTicketButton.setBorderPainted(false);
        newTicketButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newTicketButton.setFocusPainted(false);
        newTicketButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        newTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTicketButtonActionPerformed(evt);
            }
        });

        reservationLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reservationLabel.setForeground(new java.awt.Color(255, 255, 255));
        reservationLabel.setText("Reservation");
        reservationLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reservationLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationLabelMouseClicked(evt);
            }
        });

        adminButton.setBackground(new java.awt.Color(1, 50, 67));
        adminButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adminButton.setForeground(new java.awt.Color(255, 255, 255));
        adminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/settings.png"))); // NOI18N
        adminButton.setBorder(null);
        adminButton.setBorderPainted(false);
        adminButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminButton.setFocusPainted(false);
        adminButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        adminPanelLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adminPanelLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminPanelLabel.setText("Account Setting");
        adminPanelLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminPanelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanelLabelMouseClicked(evt);
            }
        });

        ticketButton.setBackground(new java.awt.Color(1, 50, 67));
        ticketButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ticketButton.setForeground(new java.awt.Color(255, 255, 255));
        ticketButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/icons8-ticket-416.png"))); // NOI18N
        ticketButton.setBorder(null);
        ticketButton.setBorderPainted(false);
        ticketButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ticketButton.setFocusPainted(false);
        ticketButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ticketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketButtonActionPerformed(evt);
            }
        });

        ticketLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ticketLabel.setForeground(new java.awt.Color(255, 255, 255));
        ticketLabel.setText("Tickets");
        ticketLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ticketLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticketLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lineSeparator4)
            .addComponent(lineSeparator5)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lineSeparator3)
                    .addComponent(lineSeparator2)
                    .addComponent(lineSeparator1)
                    .addComponent(lineSeparator6)
                    .addComponent(lineSeparator7)
                    .addComponent(lineSeparator8)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(fareCalculatorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fareCalculatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(showButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HideLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(signOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(signOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(busManagementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(newTicketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reservationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adminPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(ticketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ticketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(showButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HideLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(lineSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newTicketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busManagementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addComponent(fareCalculatorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fareCalculatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(adminPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addComponent(ticketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ticketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(lineSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addComponent(signOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(signOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        mainPanel.add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 40, 650));

        titlePanel.setBackground(new java.awt.Color(0, 0, 0));
        titlePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlePanelMouseDragged(evt);
            }
        });
        titlePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlePanelMousePressed(evt);
            }
        });

        closeButton.setBackground(new java.awt.Color(0, 0, 0));
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/close-window.png"))); // NOI18N
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.setFocusable(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        minimizeButton.setBackground(new java.awt.Color(0, 0, 0));
        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/minimize-window-filled.png"))); // NOI18N
        minimizeButton.setBorderPainted(false);
        minimizeButton.setContentAreaFilled(false);
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.setFocusable(false);
        minimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeButtonActionPerformed(evt);
            }
        });

        showUserLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        showUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        showUserLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/user.png"))); // NOI18N
        showUserLabel.setText("User");
        showUserLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showUserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showUserLabelMouseClicked(evt);
            }
        });

        showUserLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        showUserLabel1.setForeground(new java.awt.Color(255, 255, 255));
        showUserLabel1.setText("Logged in at : ");
        showUserLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(showUserLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296)
                .addComponent(showUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 406, Short.MAX_VALUE)
                .addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(showUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(showUserLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(minimizeButton)
                    .addComponent(closeButton)))
        );

        mainPanel.add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 30));

        staffIdLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        staffIdLabel.setText("Staff-ID");
        mainPanel.add(staffIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 90, 20));

        staffNameLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        staffNameLabel.setText("Staff Name");
        mainPanel.add(staffNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, 20));

        genderLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        genderLabel.setText("Gender");
        mainPanel.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 80, 20));

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        passwordLabel.setText("Password");
        mainPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, 20));

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        emailLabel.setText("Email");
        mainPanel.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, 20));

        contactnoLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        contactnoLabel.setText("Contact no");
        mainPanel.add(contactnoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, 20));

        addressLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        addressLabel.setText("Address");
        mainPanel.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, 20));

        shiftLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        shiftLabel.setText("Shift");
        mainPanel.add(shiftLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, -1, 20));

        genderLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel4.setText(":");
        mainPanel.add(genderLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 10, 20));

        genderLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel5.setText(":");
        mainPanel.add(genderLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 10, 20));

        genderLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel6.setText(":");
        mainPanel.add(genderLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 10, 20));

        genderLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel7.setText(":");
        mainPanel.add(genderLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 10, 20));

        genderLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel8.setText(":");
        mainPanel.add(genderLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 10, 20));

        genderLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel9.setText(":");
        mainPanel.add(genderLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 10, 20));

        genderLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel10.setText(":");
        mainPanel.add(genderLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 10, 20));

        genderLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel11.setText(":");
        mainPanel.add(genderLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 10, 20));
        mainPanel.add(staffIdSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 200, 10));
        mainPanel.add(staffNameSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 200, 10));

        passwordField.setBorder(null);
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordFieldKeyReleased(evt);
            }
        });
        mainPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 200, 20));
        mainPanel.add(passwordSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 200, 10));

        emailTextField.setBorder(null);
        emailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTextFieldKeyReleased(evt);
            }
        });
        mainPanel.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 200, 20));
        mainPanel.add(emailSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 200, 10));

        contactNumberTextField.setBorder(null);
        contactNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactNumberTextFieldKeyReleased(evt);
            }
        });
        mainPanel.add(contactNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 200, 20));
        mainPanel.add(contactNumberSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 200, 10));

        addressTextField.setBorder(null);
        addressTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressTextFieldKeyReleased(evt);
            }
        });
        mainPanel.add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 200, 20));
        mainPanel.add(addressSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 200, 10));

        passwordLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        passwordLabel1.setText("Confirm Password");
        mainPanel.add(passwordLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, 20));

        genderLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel12.setText(":");
        mainPanel.add(genderLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 10, 20));

        passwordField1.setBorder(null);
        passwordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordField1KeyReleased(evt);
            }
        });
        mainPanel.add(passwordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 200, 20));
        mainPanel.add(passwordSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 200, 10));

        showpass.setBackground(new java.awt.Color(255, 255, 255));
        showpass.setText("Show Password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        mainPanel.add(showpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, -1, -1));

        showpass1.setBackground(new java.awt.Color(255, 255, 255));
        showpass1.setText("Show Password");
        showpass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpass1ActionPerformed(evt);
            }
        });
        mainPanel.add(showpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, -1, -1));

        addButton1.setBackground(new java.awt.Color(255, 255, 255));
        addButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addButton1.setText("Update");
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });
        mainPanel.add(addButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, 110, 30));

        showValidationOfStaffId.setForeground(new java.awt.Color(255, 0, 0));
        mainPanel.add(showValidationOfStaffId, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 200, 15));

        showValidationOfStaffName.setForeground(new java.awt.Color(255, 0, 0));
        mainPanel.add(showValidationOfStaffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 200, 15));

        showValidationOfPassword.setForeground(new java.awt.Color(255, 0, 0));
        mainPanel.add(showValidationOfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 200, 15));

        showValidationOfEmail.setForeground(new java.awt.Color(255, 0, 0));
        mainPanel.add(showValidationOfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 200, 15));

        showValidationOfContactNumber.setForeground(new java.awt.Color(255, 0, 0));
        mainPanel.add(showValidationOfContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 200, 15));

        showValidationOfAddress.setForeground(new java.awt.Color(255, 0, 0));
        mainPanel.add(showValidationOfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 200, 15));

        showValidationOfPassword1.setForeground(new java.awt.Color(255, 0, 0));
        mainPanel.add(showValidationOfPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 200, 15));

        staffIdLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel9.setText("NULL");
        mainPanel.add(staffIdLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 200, 20));

        staffIdLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel10.setText("NULL");
        mainPanel.add(staffIdLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 200, 20));

        staffIdLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel11.setText("NULL");
        mainPanel.add(staffIdLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 200, 20));
        mainPanel.add(staffNameSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 200, 10));

        staffIdLabel12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel12.setText("NULL");
        mainPanel.add(staffIdLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 200, 20));
        mainPanel.add(staffNameSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 200, 10));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        switch(sidebar)
        {
            case 0:
            {
                sidebarPanel.setSize(220,650);
                showButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/hide.png"))); // NOI18N


                //------------------------------------------------------//
                sidebar = 1;
                break;
            }
            case 1:
            {
                sidebarPanel.setSize(40,650);
                showButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/menu.png"))); // NOI18N
                sidebar = 0;
                break;
            }
        }
        System.out.println(sidebar);
           
    }//GEN-LAST:event_showButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        BusManagement bm = new BusManagement();
        bm.setVisible(true);
        close();
    }//GEN-LAST:event_addButtonActionPerformed

    private void fareCalculatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fareCalculatorButtonActionPerformed
        FareCalculator fc = new FareCalculator();
        fc.setVisible(true);
        close();
    }//GEN-LAST:event_fareCalculatorButtonActionPerformed

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
//        DeleteDialog dialog = new DeleteDialog(new javax.swing.JFrame(), true);
//        dialog.setVisible(true);
    }//GEN-LAST:event_signOutButtonActionPerformed

    private void signOutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutLabelMouseClicked
        System.out.println("adasd");
    }//GEN-LAST:event_signOutLabelMouseClicked

    private void HideLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HideLabelMouseClicked
        switch(sidebar)
        {
            case 0:
            {
                sidebarPanel.setSize(220,650);
                showButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/hide.png"))); // NOI18N


                //------------------------------------------------------//
                sidebar = 1;
                break;
            }
            case 1:
            {
                sidebarPanel.setSize(40,650);
                showButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/menu.png"))); // NOI18N
                sidebar = 0;
                break;
            }
        }
        
    }//GEN-LAST:event_HideLabelMouseClicked

    private void fareCalculatorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fareCalculatorLabelMouseClicked
        FareCalculator fc = new FareCalculator();
        fc.setVisible(true);
        close();
    }//GEN-LAST:event_fareCalculatorLabelMouseClicked

    private void busManagementLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busManagementLabelMouseClicked
        BusManagement bm = new BusManagement();
        bm.setVisible(true);
        close();
    }//GEN-LAST:event_busManagementLabelMouseClicked

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        close();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void minimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeButtonActionPerformed
        this.setState(AccountSetting.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonActionPerformed

    private void titlePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePanelMouseDragged
        int kordinateX = evt.getXOnScreen();
        int kordinateY = evt.getYOnScreen();
        
        this.setLocation(kordinateX-mousepX, kordinateY-mousepY);
    }//GEN-LAST:event_titlePanelMouseDragged

    private void titlePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePanelMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
        
    }//GEN-LAST:event_titlePanelMousePressed

    private void showUserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showUserLabelMouseClicked
        ShowStaffDetail dialog = new ShowStaffDetail(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_showUserLabelMouseClicked

    private void newTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTicketButtonActionPerformed
        NewTicketPanel ntp = new NewTicketPanel();
        ntp.setVisible(true);
        close();
    }//GEN-LAST:event_newTicketButtonActionPerformed

    private void reservationLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationLabelMouseClicked
        NewTicketPanel ntp = new NewTicketPanel();
        ntp.setVisible(true);
        close();
    }//GEN-LAST:event_reservationLabelMouseClicked

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButtonActionPerformed

    private void adminPanelLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPanelLabelMouseClicked

    private void ticketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketButtonActionPerformed
        TicketDetails tc = new TicketDetails();
        tc.setVisible(true);
        close();
    }//GEN-LAST:event_ticketButtonActionPerformed

    private void ticketLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketLabelMouseClicked
        TicketDetails tc = new TicketDetails();
        tc.setVisible(true);
        close();
    }//GEN-LAST:event_ticketLabelMouseClicked

    private void passwordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyReleased
//        String PATTERN = "^[a-zA-Z0-9]{0,15}$";
//        Pattern patt = Pattern.compile(PATTERN);
//        Matcher match = patt.matcher(passwordField.getText());
//        if(!match.matches())
//        {
//            showValidationOfPassword.setText("Password field is Incorrect");
//            passwordField.setForeground(Color.red);
//            pvalid = 0;
//        }
//        if(passwordField.getText().equals(""))
//        {
//            showValidationOfPassword.setText("Password field cannot be Empty");
//            passwordField.setForeground(Color.white);
//            pvalid = 0;
//        }
//        if(match.matches())
//        {
//            showValidationOfPassword.setText(null);
//            passwordField.setForeground(Color.white);
//            pvalid = 1;
//        }
    }//GEN-LAST:event_passwordFieldKeyReleased

    private void emailTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextFieldKeyReleased
//        String PATTERN = "^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$";
//        Pattern patt = Pattern.compile(PATTERN);
//        Matcher match = patt.matcher(emailTextField.getText());
//        if(!match.matches())
//        {
//            showValidationOfEmail.setText("Email Id is incorrect!");
//            emailTextField.setForeground(Color.red);
//            emailvalid = 0;
//        }
//        if(emailTextField.getText().equals(""))
//        {
//            showValidationOfEmail.setText(null);
//            emailTextField.setForeground(Color.white);
//            emailvalid = 0;
//        }
//        if(match.matches())
//        {
//            showValidationOfEmail.setText(null);
//            emailTextField.setForeground(Color.white);
//            emailvalid = 1;
//        }
    }//GEN-LAST:event_emailTextFieldKeyReleased

    private void contactNumberTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNumberTextFieldKeyReleased
//        String PATTERN = "^[0-9]{10}$";
//        Pattern patt = Pattern.compile(PATTERN);
//        Matcher match = patt.matcher(contactNumberTextField.getText());
//        if(!match.matches())
//        {
//            showValidationOfContactNumber.setText("Contact Number should be 10 digit!");
//            contactNumberTextField.setForeground(Color.red);
//            contactnumbervalid = 0;
//        }
//        if(contactNumberTextField.getText().equals(""))
//        {
//            showValidationOfContactNumber.setText(null);
//            contactNumberTextField.setForeground(Color.white);
//            contactnumbervalid = 0;
//        }
//        if(match.matches())
//        {
//            showValidationOfContactNumber.setText(null);
//            contactNumberTextField.setForeground(Color.white);
//            contactnumbervalid = 1;
//        }
    }//GEN-LAST:event_contactNumberTextFieldKeyReleased

    private void addressTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTextFieldKeyReleased
//        String PATTERN = "^[a-zA-Z\\s]{2,25}+$";
//        Pattern patt = Pattern.compile(PATTERN);
//        Matcher match = patt.matcher(addressTextField.getText());
//        if(!match.matches())
//        {
//            showValidationOfAddress.setText("Naming is incorrect!");
//            addressTextField.setForeground(Color.red);
//            addressvalid = 0;
//        }
//        if(addressTextField.getText().equals(""))
//        {
//            showValidationOfAddress.setText(null);
//            addressTextField.setForeground(Color.white);
//            addressvalid = 0;
//        }
//        if(match.matches())
//        {
//            showValidationOfAddress.setText(null);
//            addressTextField.setForeground(Color.white);
//            addressvalid = 1;
//        }
    }//GEN-LAST:event_addressTextFieldKeyReleased

    private void passwordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordField1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordField1KeyReleased

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        if(showpass.isSelected())
        {
            passwordField.setEchoChar((char)0);
        }
        else
        {
            passwordField.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassActionPerformed

    private void showpass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showpass1ActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        String sid1=staffIdTextField.getText();
        String suser1=staffNameTextField.getText();
        String spass1=passwordField.getText();
        StringBuffer sb = new StringBuffer(spass1);
        String spass = new String(sb);

        String semail1=emailTextField.getText();
        String scontactno1=contactNumberTextField.getText();
        String saddress1=addressTextField.getText();
        //------------//
        SimpleDateFormat format = new SimpleDateFormat("yyyy-M-dd");
        Date d1 = new Date();
        String sdate = new String(format.format(d1));
        //------------//
        String sidcategory1 = "staff";
        String sgender="Male";
        if(female.isSelected())
        {
            sgender="Female";
        }
        String sshift="Morning";
        if(day.isSelected())
        {
            sshift="Day";
        }
        int esivalid=0, esnvalid=0, epvalid=0, eevalid=0, ecnvalid=0, eavalid=0;
        if(sid1.equals(""))
        {
            showValidationOfStaffId.setText("Staff ID Field is Empty!");
            esivalid = 0;
        }
        else{
            showValidationOfStaffId.setText(null);
            esivalid = 1;
        }
        if(suser1.equals(""))
        {
            showValidationOfStaffName.setText("Staff Name Field is Empty!");
            esnvalid = 0;
        }
        else{
            showValidationOfStaffName.setText(null);
            esnvalid = 1;
        }
        if(spass1.equals(""))
        {
            showValidationOfPassword.setText("Password Field is Empty!");
            epvalid = 0;
        }
        else{
            showValidationOfPassword.setText(null);
            epvalid = 1;
        }
        if(semail1.equals(""))
        {
            showValidationOfEmail.setText("Email ID Field is Empty!");
            eevalid = 0;
        }
        else{
            showValidationOfEmail.setText(null);
            eevalid = 1;
        }
        if(scontactno1.equals(""))
        {
            showValidationOfContactNumber.setText("Contact Number Field is Empty!");
            ecnvalid = 0;
        }
        else{
            showValidationOfContactNumber.setText(null);
            ecnvalid = 1;
        }
        if(saddress1.equals(""))
        {
            showValidationOfAddress.setText("Address Field is Empty!");
            eavalid = 0;
        }
        else{
            showValidationOfAddress.setText(null);
            eavalid = 1;
        }
        if(esivalid==1 && esnvalid==1 && epvalid==1 && eevalid==1 && ecnvalid==1 && eavalid==1)
        {
            try
            {

                Connection conn;
                Class.forName("com.mysql.jdbc.Driver");
                conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/staffdetails","root","");
                PreparedStatement pstmt = conn.prepareStatement("INSERT INTO staffdet VALUES(?,?,?,?,?,?,?,?,?,?)");

                if( ivalid == 1 && pvalid == 1 && snvalid == 1 && emailvalid == 1 && contactnumbervalid == 1 && addressvalid == 1)
                {
                    pstmt.setString(1,sid1);
                    pstmt.setString(2,spass);
                    pstmt.setString(3,sidcategory1);
                    pstmt.setString(4,suser1);
                    pstmt.setString(5,sgender);
                    pstmt.setString(6,saddress1);
                    pstmt.setString(7,scontactno1);
                    pstmt.setString(8,semail1);
                    pstmt.setString(9,sdate);
                    pstmt.setString(10,sshift);

                    pstmt.executeUpdate();

                    JOptionPane.showMessageDialog(this, "You have Successfully Submitted Staff Details");
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Invalid Data Entered!");

                }
            }
            catch(Exception e)
            {
                System.out.println(e);
                //e.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(null,"Field cannot be left Empty");

        }
    }//GEN-LAST:event_addButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountSetting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HideLabel;
    private javax.swing.JButton addButton;
    public javax.swing.JButton addButton1;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JSeparator addressSeparator;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton adminButton;
    private javax.swing.JLabel adminPanelLabel;
    private javax.swing.JLabel busManagementLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JSeparator contactNumberSeparator;
    private javax.swing.JTextField contactNumberTextField;
    private javax.swing.JLabel contactnoLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JSeparator emailSeparator;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton fareCalculatorButton;
    private javax.swing.JLabel fareCalculatorLabel;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel genderLabel10;
    private javax.swing.JLabel genderLabel11;
    private javax.swing.JLabel genderLabel12;
    private javax.swing.JLabel genderLabel4;
    private javax.swing.JLabel genderLabel5;
    private javax.swing.JLabel genderLabel6;
    private javax.swing.JLabel genderLabel7;
    private javax.swing.JLabel genderLabel8;
    private javax.swing.JLabel genderLabel9;
    private javax.swing.JSeparator lineSeparator1;
    private javax.swing.JSeparator lineSeparator2;
    private javax.swing.JSeparator lineSeparator3;
    private javax.swing.JSeparator lineSeparator4;
    private javax.swing.JSeparator lineSeparator5;
    private javax.swing.JSeparator lineSeparator6;
    private javax.swing.JSeparator lineSeparator7;
    private javax.swing.JSeparator lineSeparator8;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton minimizeButton;
    private javax.swing.JButton newTicketButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JSeparator passwordSeparator;
    private javax.swing.JSeparator passwordSeparator1;
    private javax.swing.JLabel reservationLabel;
    private javax.swing.ButtonGroup shiftButtonGroup;
    private javax.swing.JLabel shiftLabel;
    private javax.swing.JButton showButton;
    private javax.swing.JLabel showUserLabel;
    private javax.swing.JLabel showUserLabel1;
    private javax.swing.JLabel showValidationOfAddress;
    private javax.swing.JLabel showValidationOfContactNumber;
    private javax.swing.JLabel showValidationOfEmail;
    private javax.swing.JLabel showValidationOfPassword;
    private javax.swing.JLabel showValidationOfPassword1;
    private javax.swing.JLabel showValidationOfStaffId;
    private javax.swing.JLabel showValidationOfStaffName;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JCheckBox showpass1;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JButton signOutButton;
    private javax.swing.JLabel signOutLabel;
    private javax.swing.JLabel staffIdLabel;
    private javax.swing.JLabel staffIdLabel10;
    private javax.swing.JLabel staffIdLabel11;
    private javax.swing.JLabel staffIdLabel12;
    private javax.swing.JLabel staffIdLabel9;
    private javax.swing.JSeparator staffIdSeperator;
    private javax.swing.JLabel staffNameLabel;
    private javax.swing.JSeparator staffNameSeparator;
    private javax.swing.JSeparator staffNameSeparator1;
    private javax.swing.JSeparator staffNameSeparator2;
    private javax.swing.JButton ticketButton;
    private javax.swing.JLabel ticketLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
