/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busticket;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author pravinewa
 */
public class NewTicketPanel extends javax.swing.JFrame {
    static int sidebar = 0;
    static int mousepX, mousepY;  
    /**
     * Creates new form OpenPanel
     */
    public NewTicketPanel() {
        initComponents();
    }
    private void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();
        showButton = new javax.swing.JButton();
        lineSeparator3 = new javax.swing.JSeparator();
        lineSeparator2 = new javax.swing.JSeparator();
        lineSeparator1 = new javax.swing.JSeparator();
        lineSeparator4 = new javax.swing.JSeparator();
        lineSeparator5 = new javax.swing.JSeparator();
        signOutLabel = new javax.swing.JLabel();
        HideLabel = new javax.swing.JLabel();
        fareCalculatorLabel = new javax.swing.JLabel();
        busManagementLabel = new javax.swing.JLabel();
        lineSeparator6 = new javax.swing.JSeparator();
        reservationButton = new javax.swing.JButton();
        reservationLabel = new javax.swing.JLabel();
        adminButton = new javax.swing.JButton();
        lineSeparator7 = new javax.swing.JSeparator();
        adminPanelLabel = new javax.swing.JLabel();
        ticketButton = new javax.swing.JButton();
        lineSeparator8 = new javax.swing.JSeparator();
        ticketLabel = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        minimizeButton = new javax.swing.JButton();
        showUserLabel = new javax.swing.JLabel();
        showUserLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CIDLabel = new javax.swing.JLabel();
        PIDLabel = new javax.swing.JLabel();
        PIDComboBox = new javax.swing.JComboBox<>();
        CIDComboBox = new javax.swing.JComboBox<>();
        CIDLabel1 = new javax.swing.JLabel();
        CIDLabel2 = new javax.swing.JLabel();
        CIDLabel3 = new javax.swing.JLabel();
        CIDLabel4 = new javax.swing.JLabel();
        ownerNameTextField = new javax.swing.JTextField();
        ownerNameSeparator = new javax.swing.JSeparator();
        ownerNameTextField1 = new javax.swing.JTextField();
        ownerNameSeparator1 = new javax.swing.JSeparator();
        ownerNameTextField2 = new javax.swing.JTextField();
        ownerNameSeparator2 = new javax.swing.JSeparator();
        getBusDetailsButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        CIDComboBox1 = new javax.swing.JComboBox<>();
        CIDLabel6 = new javax.swing.JLabel();
        loadButton = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CIDLabel7 = new javax.swing.JLabel();
        CIDLabel8 = new javax.swing.JLabel();
        CIDLabel5 = new javax.swing.JLabel();
        submitButton2 = new javax.swing.JButton();
        genderLabel4 = new javax.swing.JLabel();
        genderLabel5 = new javax.swing.JLabel();
        genderLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        mainPanel.setPreferredSize(new java.awt.Dimension(1070, 530));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarPanel.setBackground(new java.awt.Color(1, 50, 67));

        addButton.setBackground(new java.awt.Color(1, 50, 67));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/icons8-calendar-416.png"))); // NOI18N
        addButton.setBorder(null);
        addButton.setBorderPainted(false);
        addButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addButton.setFocusPainted(false);
        addButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(1, 50, 67));
        searchButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/icons8-calculator-500.png"))); // NOI18N
        searchButton.setBorder(null);
        searchButton.setBorderPainted(false);
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.setFocusPainted(false);
        searchButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        signOutButton.setBackground(new java.awt.Color(1, 50, 67));
        signOutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signOutButton.setForeground(new java.awt.Color(255, 255, 255));
        signOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/sign-out.png"))); // NOI18N
        signOutButton.setBorder(null);
        signOutButton.setBorderPainted(false);
        signOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOutButton.setFocusPainted(false);
        signOutButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });

        showButton.setBackground(new java.awt.Color(1, 50, 67));
        showButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showButton.setForeground(new java.awt.Color(255, 255, 255));
        showButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/menu.png"))); // NOI18N
        showButton.setBorder(null);
        showButton.setBorderPainted(false);
        showButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showButton.setFocusPainted(false);
        showButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        signOutLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signOutLabel.setForeground(new java.awt.Color(255, 255, 255));
        signOutLabel.setText("Sign Out");
        signOutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signOutLabelMouseClicked(evt);
            }
        });

        HideLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HideLabel.setForeground(new java.awt.Color(255, 255, 255));
        HideLabel.setText("Hide");
        HideLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HideLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HideLabelMouseClicked(evt);
            }
        });

        fareCalculatorLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fareCalculatorLabel.setForeground(new java.awt.Color(255, 255, 255));
        fareCalculatorLabel.setText("Fare Calculator");
        fareCalculatorLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fareCalculatorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fareCalculatorLabelMouseClicked(evt);
            }
        });

        busManagementLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        busManagementLabel.setForeground(new java.awt.Color(255, 255, 255));
        busManagementLabel.setText("Bus Management");
        busManagementLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        busManagementLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busManagementLabelMouseClicked(evt);
            }
        });

        reservationButton.setBackground(new java.awt.Color(1, 50, 67));
        reservationButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reservationButton.setForeground(new java.awt.Color(255, 255, 255));
        reservationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/icons8-new-ticket-416.png"))); // NOI18N
        reservationButton.setBorder(null);
        reservationButton.setBorderPainted(false);
        reservationButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reservationButton.setFocusPainted(false);
        reservationButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        reservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationButtonActionPerformed(evt);
            }
        });

        reservationLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reservationLabel.setForeground(new java.awt.Color(255, 255, 255));
        reservationLabel.setText("Reservation");
        reservationLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reservationLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationLabelMouseClicked(evt);
            }
        });

        adminButton.setBackground(new java.awt.Color(1, 50, 67));
        adminButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adminButton.setForeground(new java.awt.Color(255, 255, 255));
        adminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/settings.png"))); // NOI18N
        adminButton.setBorder(null);
        adminButton.setBorderPainted(false);
        adminButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminButton.setFocusPainted(false);
        adminButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        adminPanelLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adminPanelLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminPanelLabel.setText("Account Setting");
        adminPanelLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminPanelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanelLabelMouseClicked(evt);
            }
        });

        ticketButton.setBackground(new java.awt.Color(1, 50, 67));
        ticketButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ticketButton.setForeground(new java.awt.Color(255, 255, 255));
        ticketButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/icons8-ticket-416.png"))); // NOI18N
        ticketButton.setBorder(null);
        ticketButton.setBorderPainted(false);
        ticketButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ticketButton.setFocusPainted(false);
        ticketButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ticketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketButtonActionPerformed(evt);
            }
        });

        ticketLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ticketLabel.setForeground(new java.awt.Color(255, 255, 255));
        ticketLabel.setText("Tickets");
        ticketLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ticketLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticketLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lineSeparator4)
            .addComponent(lineSeparator5)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lineSeparator3)
                    .addComponent(lineSeparator2)
                    .addComponent(lineSeparator1)
                    .addComponent(lineSeparator6)
                    .addComponent(lineSeparator7)
                    .addComponent(lineSeparator8)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fareCalculatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(showButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HideLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(signOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(signOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(busManagementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(reservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reservationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adminPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(ticketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ticketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(showButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HideLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(lineSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busManagementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fareCalculatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(adminPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addComponent(ticketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ticketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(lineSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addComponent(signOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(signOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        mainPanel.add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 40, 650));

        titlePanel.setBackground(new java.awt.Color(0, 0, 0));
        titlePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlePanelMouseDragged(evt);
            }
        });
        titlePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlePanelMousePressed(evt);
            }
        });

        closeButton.setBackground(new java.awt.Color(0, 0, 0));
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/close-window.png"))); // NOI18N
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.setFocusable(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        minimizeButton.setBackground(new java.awt.Color(0, 0, 0));
        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/minimize-window-filled.png"))); // NOI18N
        minimizeButton.setBorderPainted(false);
        minimizeButton.setContentAreaFilled(false);
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.setFocusable(false);
        minimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeButtonActionPerformed(evt);
            }
        });

        showUserLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        showUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        showUserLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/user.png"))); // NOI18N
        showUserLabel.setText("User");
        showUserLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showUserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showUserLabelMouseClicked(evt);
            }
        });

        showUserLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        showUserLabel1.setForeground(new java.awt.Color(255, 255, 255));
        showUserLabel1.setText("Logged in at : ");
        showUserLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(showUserLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296)
                .addComponent(showUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 406, Short.MAX_VALUE)
                .addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(showUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(showUserLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(minimizeButton)
                    .addComponent(closeButton)))
        );

        mainPanel.add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CIDLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CIDLabel.setText("/  YYYY");
        jPanel2.add(CIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 50, 20));

        PIDLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PIDLabel.setText("Destination ");
        jPanel2.add(PIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, 30));

        PIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose destination", "Bhaktapur", "Damauli", "Janakpur", "Kathmandu", "Kritipur", "Kushma", "Lumbini", "Pokhara" }));
        jPanel2.add(PIDComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 240, 30));

        CIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose source station", "Bhaktapur", "Damauli", "Janakpur", "Kathmandu", "Kritipur", "Kushma", "Lumbini", "Pokhara" }));
        jPanel2.add(CIDComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 240, 30));

        CIDLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CIDLabel1.setText("Source Station ");
        jPanel2.add(CIDLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 100, 30));

        CIDLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CIDLabel2.setText("Enter Date ");
        jPanel2.add(CIDLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 80, 20));

        CIDLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CIDLabel3.setText("DD");
        jPanel2.add(CIDLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 20, 20));

        CIDLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CIDLabel4.setText("/  MM");
        jPanel2.add(CIDLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 40, 20));

        ownerNameTextField.setBorder(null);
        ownerNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ownerNameTextFieldKeyReleased(evt);
            }
        });
        jPanel2.add(ownerNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 40, 20));
        jPanel2.add(ownerNameSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 40, 10));

        ownerNameTextField1.setBorder(null);
        ownerNameTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ownerNameTextField1KeyReleased(evt);
            }
        });
        jPanel2.add(ownerNameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 40, 20));
        jPanel2.add(ownerNameSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 40, 10));

        ownerNameTextField2.setBorder(null);
        ownerNameTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ownerNameTextField2KeyReleased(evt);
            }
        });
        jPanel2.add(ownerNameTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 40, 20));
        jPanel2.add(ownerNameSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 40, 10));

        getBusDetailsButton.setBackground(new java.awt.Color(255, 255, 255));
        getBusDetailsButton.setText("Get Bus Details");
        getBusDetailsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getBusDetailsButton.setFocusable(false);
        getBusDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBusDetailsButtonActionPerformed(evt);
            }
        });
        jPanel2.add(getBusDetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 150, 30));

        resetButton.setBackground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset");
        resetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetButton.setFocusable(false);
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel2.add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 80, 30));

        CIDComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose source station", "Bhaktapur", "Damauli", "Janakpur", "Kathmandu", "Kritipur", "Kushma", "Lumbini", "Pokhara" }));
        jPanel2.add(CIDComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 470, 30));

        CIDLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CIDLabel6.setText("Select Bus From List & Click Load :");
        jPanel2.add(CIDLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 220, 30));

        loadButton.setBackground(new java.awt.Color(255, 255, 255));
        loadButton.setText("Load");
        loadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loadButton.setFocusable(false);
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });
        jPanel2.add(loadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 120, 30));

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel64.setText("28");
        jPanel2.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 20, -1));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel60.setText("29");
        jPanel2.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 20, -1));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel61.setText("27");
        jPanel2.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 20, -1));

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel62.setText("31");
        jPanel2.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 20, -1));

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel63.setText("30");
        jPanel2.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 20, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel48.setText("21");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 20, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel49.setText("22");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 20, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel50.setText("20");
        jPanel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 20, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel51.setText("19");
        jPanel2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 20, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel52.setText("25");
        jPanel2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 20, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel53.setText("26");
        jPanel2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 20, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel54.setText("24");
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 20, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel55.setText("23");
        jPanel2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 20, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel56.setText("18");
        jPanel2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 20, -1));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel57.setText("17");
        jPanel2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 20, -1));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel58.setText("16");
        jPanel2.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 20, -1));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel59.setText("15");
        jPanel2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 20, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("9");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 10, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel41.setText("10");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 20, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel42.setText("8");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 10, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel43.setText("7");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 10, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel44.setText("13");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 20, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel45.setText("14");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 20, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel46.setText("12");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 20, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel47.setText("11");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 20, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("6");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, 10, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setText("5");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 10, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("4");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 10, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("3");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 10, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("2");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 10, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("1");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 10, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel26.setText("jLabel2");
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel26MouseExited(evt);
            }
        });
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 30, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel9.setText("jLabel2");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 30, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 340, 10));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel27.setText("jLabel2");
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel27MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel27MouseExited(evt);
            }
        });
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 30, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel19.setText("jLabel2");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/driver.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 50, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel18.setText("jLabel2");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 30, 30));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel25.setText("jLabel2");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel25MouseExited(evt);
            }
        });
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 30, 30));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel24.setText("jLabel2");
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel24MouseExited(evt);
            }
        });
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 30, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel20.setText("jLabel2");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel20MouseExited(evt);
            }
        });
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 30, 30));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel31.setText("jLabel2");
        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel31MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel31MouseExited(evt);
            }
        });
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 30, 30));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel23.setText("jLabel2");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23MouseExited(evt);
            }
        });
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 30, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel21.setText("jLabel2");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 30, 30));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel28.setText("jLabel2");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel28MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel28MouseExited(evt);
            }
        });
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 30, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel15.setText("jLabel2");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 30, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel14.setText("jLabel2");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 30, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel10.setText("jLabel2");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 30, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel4.setText("jLabel2");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 30, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel22.setText("jLabel2");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22MouseExited(evt);
            }
        });
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 30, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel6.setText("jLabel2");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 30, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel8.setText("jLabel2");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 30, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel12.setText("jLabel2");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 30, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel17.setText("jLabel2");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
        });
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 30, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel13.setText("jLabel2");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 30, 30));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel33.setText("jLabel2");
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel33MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel33MouseExited(evt);
            }
        });
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 30, 30));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel30.setText("jLabel2");
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel30MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel30MouseExited(evt);
            }
        });
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 30, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 340, 10));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel7.setText("jLabel2");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 30, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel16.setText("jLabel2");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 30, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel29.setText("jLabel2");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel29MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel29MouseExited(evt);
            }
        });
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel5.setText("jLabel2");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 30, 30));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel32.setText("jLabel2");
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel32MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel32MouseExited(evt);
            }
        });
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 30, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png"))); // NOI18N
        jLabel11.setText("jLabel2");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/bus-310765_1280 (1).png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 900, 330));

        CIDLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CIDLabel7.setText("You Have Selected : ");
        jPanel2.add(CIDLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 290, 30));

        CIDLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CIDLabel8.setText("Bus ID :");
        jPanel2.add(CIDLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 150, 30));

        CIDLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CIDLabel5.setText("D.O.J. :");
        jPanel2.add(CIDLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 190, 30));

        submitButton2.setBackground(new java.awt.Color(255, 255, 255));
        submitButton2.setText("Make Reservation");
        submitButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton2.setFocusable(false);
        submitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(submitButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 150, 40));

        genderLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel4.setText(":");
        jPanel2.add(genderLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 10, 30));

        genderLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel5.setText(":");
        jPanel2.add(genderLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 10, 20));

        genderLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel6.setText(":");
        jPanel2.add(genderLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 10, 30));

        mainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 990, 150));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        switch(sidebar)
        {
            case 0:
            {
                sidebarPanel.setSize(220,650);
                showButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/hide.png"))); // NOI18N


                //------------------------------------------------------//
                sidebar = 1;
                break;
            }
            case 1:
            {
                sidebarPanel.setSize(40,650);
                showButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/menu.png"))); // NOI18N
                sidebar = 0;
                break;
            }
        }
        System.out.println(sidebar);
           
    }//GEN-LAST:event_showButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        BusManagement bm = new BusManagement();
        bm.setVisible(true);
        close();
    }//GEN-LAST:event_addButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        FareCalculator fc = new FareCalculator();
        fc.setVisible(true);
        close();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
//        DeleteDialog dialog = new DeleteDialog(new javax.swing.JFrame(), true);
//        dialog.setVisible(true);
    }//GEN-LAST:event_signOutButtonActionPerformed

    private void signOutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutLabelMouseClicked
        System.out.println("adasd");
    }//GEN-LAST:event_signOutLabelMouseClicked

    private void HideLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HideLabelMouseClicked
        switch(sidebar)
        {
            case 0:
            {
                sidebarPanel.setSize(220,650);
                showButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/hide.png"))); // NOI18N


                //------------------------------------------------------//
                sidebar = 1;
                break;
            }
            case 1:
            {
                sidebarPanel.setSize(40,650);
                showButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/menu.png"))); // NOI18N
                sidebar = 0;
                break;
            }
        }
        
    }//GEN-LAST:event_HideLabelMouseClicked

    private void fareCalculatorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fareCalculatorLabelMouseClicked
        FareCalculator fc = new FareCalculator();
        fc.setVisible(true);
        close();
    }//GEN-LAST:event_fareCalculatorLabelMouseClicked

    private void busManagementLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busManagementLabelMouseClicked
        BusManagement bm = new BusManagement();
        bm.setVisible(true);
        close();
    }//GEN-LAST:event_busManagementLabelMouseClicked

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        close();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void minimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeButtonActionPerformed
        this.setState(NewTicketPanel.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonActionPerformed

    private void titlePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePanelMouseDragged
        int kordinateX = evt.getXOnScreen();
        int kordinateY = evt.getYOnScreen();
        
        this.setLocation(kordinateX-mousepX, kordinateY-mousepY);
    }//GEN-LAST:event_titlePanelMouseDragged

    private void titlePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePanelMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
        
    }//GEN-LAST:event_titlePanelMousePressed

    private void showUserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showUserLabelMouseClicked
        ShowStaffDetail dialog = new ShowStaffDetail(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_showUserLabelMouseClicked

    private void reservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationButtonActionPerformed

    private void reservationLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationLabelMouseClicked

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        AccountSetting as = new AccountSetting();
        as.setVisible(true);
        close();
    }//GEN-LAST:event_adminButtonActionPerformed

    private void adminPanelLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelLabelMouseClicked
        AccountSetting as = new AccountSetting();
        as.setVisible(true);
        close();
    }//GEN-LAST:event_adminPanelLabelMouseClicked

    private void ticketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketButtonActionPerformed
        TicketDetails td = new TicketDetails();
        td.setVisible(true);
        close();
    }//GEN-LAST:event_ticketButtonActionPerformed

    private void ticketLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketLabelMouseClicked
        TicketDetails td = new TicketDetails();
        td.setVisible(true);
        close();
    }//GEN-LAST:event_ticketLabelMouseClicked

    private void ownerNameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ownerNameTextFieldKeyReleased
    }//GEN-LAST:event_ownerNameTextFieldKeyReleased

    private void ownerNameTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ownerNameTextField1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerNameTextField1KeyReleased

    private void ownerNameTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ownerNameTextField2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerNameTextField2KeyReleased

    private void getBusDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBusDetailsButtonActionPerformed
        jPanel2.setSize(990, 220);
        getBusDetailsButton.setEnabled(false);
    }//GEN-LAST:event_getBusDetailsButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        jPanel2.setSize(990, 150);
        getBusDetailsButton.setEnabled(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void submitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton2ActionPerformed
        PassengerDetails dialog = new PassengerDetails(new javax.swing.JFrame(), true);
        dialog.setVisible(true);        
    }//GEN-LAST:event_submitButton2ActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        jPanel2.setSize(990, 640);
    }//GEN-LAST:event_loadButtonActionPerformed

    private void jLabel26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseEntered
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel26MouseEntered

    private void jLabel26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseExited
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel26MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseEntered
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel27MouseEntered

    private void jLabel27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseExited
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel27MouseExited

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel19MouseExited

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel18MouseExited

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel25MouseEntered

    private void jLabel25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseExited
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel25MouseExited

    private void jLabel24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseEntered
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel24MouseEntered

    private void jLabel24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseExited
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel24MouseExited

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel20MouseEntered

    private void jLabel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseExited
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel20MouseExited

    private void jLabel31MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseEntered
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel31MouseEntered

    private void jLabel31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseExited
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel31MouseExited

    private void jLabel23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseEntered
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel23MouseEntered

    private void jLabel23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseExited
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel23MouseExited

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel21MouseExited

    private void jLabel28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseEntered
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel28MouseEntered

    private void jLabel28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseExited
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel28MouseExited

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseEntered
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel22MouseEntered

    private void jLabel22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseExited
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel22MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel32MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseEntered
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel32MouseEntered

    private void jLabel32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseExited
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel32MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel29MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseEntered
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel29MouseEntered

    private void jLabel29MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseExited
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel29MouseExited

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseEntered
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel30MouseEntered

    private void jLabel30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseExited
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel30MouseExited

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel17MouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel33MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseEntered
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger1.png")));
    }//GEN-LAST:event_jLabel33MouseEntered

    private void jLabel33MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseExited
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/pasenger.png")));
    }//GEN-LAST:event_jLabel33MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewTicketPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CIDComboBox;
    private javax.swing.JComboBox<String> CIDComboBox1;
    private javax.swing.JLabel CIDLabel;
    private javax.swing.JLabel CIDLabel1;
    private javax.swing.JLabel CIDLabel2;
    private javax.swing.JLabel CIDLabel3;
    private javax.swing.JLabel CIDLabel4;
    private javax.swing.JLabel CIDLabel5;
    private javax.swing.JLabel CIDLabel6;
    private javax.swing.JLabel CIDLabel7;
    private javax.swing.JLabel CIDLabel8;
    private javax.swing.JLabel HideLabel;
    private javax.swing.JComboBox<String> PIDComboBox;
    private javax.swing.JLabel PIDLabel;
    private javax.swing.JButton addButton;
    private javax.swing.JButton adminButton;
    private javax.swing.JLabel adminPanelLabel;
    private javax.swing.JLabel busManagementLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel fareCalculatorLabel;
    private javax.swing.JLabel genderLabel4;
    private javax.swing.JLabel genderLabel5;
    private javax.swing.JLabel genderLabel6;
    private javax.swing.JButton getBusDetailsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator lineSeparator1;
    private javax.swing.JSeparator lineSeparator2;
    private javax.swing.JSeparator lineSeparator3;
    private javax.swing.JSeparator lineSeparator4;
    private javax.swing.JSeparator lineSeparator5;
    private javax.swing.JSeparator lineSeparator6;
    private javax.swing.JSeparator lineSeparator7;
    private javax.swing.JSeparator lineSeparator8;
    private javax.swing.JButton loadButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton minimizeButton;
    private javax.swing.JSeparator ownerNameSeparator;
    private javax.swing.JSeparator ownerNameSeparator1;
    private javax.swing.JSeparator ownerNameSeparator2;
    private javax.swing.JTextField ownerNameTextField;
    private javax.swing.JTextField ownerNameTextField1;
    private javax.swing.JTextField ownerNameTextField2;
    private javax.swing.JButton reservationButton;
    private javax.swing.JLabel reservationLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton showButton;
    private javax.swing.JLabel showUserLabel;
    private javax.swing.JLabel showUserLabel1;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JButton signOutButton;
    private javax.swing.JLabel signOutLabel;
    private javax.swing.JButton submitButton2;
    private javax.swing.JButton ticketButton;
    private javax.swing.JLabel ticketLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
