/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busticket;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author pravinewa
 */
public class PassengerTicket extends javax.swing.JDialog {
    static int ivalid = 0, pvalid = 0, snvalid = 0, emailvalid = 0, contactnumbervalid = 0, addressvalid = 0;
    
    /**
     * Creates new form AddStaff
     */
    public PassengerTicket(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        staffIdLabel = new javax.swing.JLabel();
        staffNameSeparator = new javax.swing.JSeparator();
        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        staffNameLabel1 = new javax.swing.JLabel();
        staffIdLabel1 = new javax.swing.JLabel();
        staffIdLabel2 = new javax.swing.JLabel();
        staffIdLabel3 = new javax.swing.JLabel();
        staffIdLabel4 = new javax.swing.JLabel();
        staffIdLabel5 = new javax.swing.JLabel();
        staffIdLabel6 = new javax.swing.JLabel();
        staffIdLabel7 = new javax.swing.JLabel();
        staffIdLabel8 = new javax.swing.JLabel();
        staffIdLabel9 = new javax.swing.JLabel();
        staffIdLabel10 = new javax.swing.JLabel();
        staffIdLabel11 = new javax.swing.JLabel();
        staffIdLabel12 = new javax.swing.JLabel();
        cancelButton1 = new javax.swing.JButton();
        staffIdLabel13 = new javax.swing.JLabel();
        staffIdLabel14 = new javax.swing.JLabel();
        staffIdLabel15 = new javax.swing.JLabel();
        staffIdLabel16 = new javax.swing.JLabel();
        staffIdLabel17 = new javax.swing.JLabel();
        staffIdLabel18 = new javax.swing.JLabel();
        staffIdLabel19 = new javax.swing.JLabel();
        staffIdLabel20 = new javax.swing.JLabel();
        staffIdLabel21 = new javax.swing.JLabel();
        staffIdLabel22 = new javax.swing.JLabel();
        staffIdLabel23 = new javax.swing.JLabel();
        staffIdLabel24 = new javax.swing.JLabel();
        staffIdLabel25 = new javax.swing.JLabel();
        staffIdLabel26 = new javax.swing.JLabel();
        staffIdLabel27 = new javax.swing.JLabel();
        staffIdLabel28 = new javax.swing.JLabel();
        staffIdLabel29 = new javax.swing.JLabel();
        staffIdLabel31 = new javax.swing.JLabel();
        staffIdLabel32 = new javax.swing.JLabel();
        staffIdLabel33 = new javax.swing.JLabel();
        staffIdLabel34 = new javax.swing.JLabel();
        staffIdLabel35 = new javax.swing.JLabel();
        staffIdLabel30 = new javax.swing.JLabel();
        staffNameSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.9F);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 50, 67));
        jPanel1.setPreferredSize(new java.awt.Dimension(440, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staffIdLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel.setText("Bus Identifier                     ");
        jPanel1.add(staffIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 220, 20));
        jPanel1.add(staffNameSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 680, 10));

        addButton.setBackground(new java.awt.Color(255, 255, 255));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addButton.setText("Print Ticket");
        addButton.setFocusable(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 230, 30));

        cancelButton.setBackground(new java.awt.Color(255, 255, 255));
        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButton.setText("Close");
        cancelButton.setFocusable(false);
        cancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 230, 30));

        staffNameLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffNameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        staffNameLabel1.setText("Mobile Number");
        jPanel1.add(staffNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 120, 20));

        staffIdLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel1.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel1.setText("Seat Number");
        jPanel1.add(staffIdLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 150, 20));

        staffIdLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel2.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel2.setText("NULL");
        jPanel1.add(staffIdLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 190, 20));

        staffIdLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel3.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel3.setText("Booked By Agent        ");
        jPanel1.add(staffIdLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 220, 20));

        staffIdLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel4.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel4.setText(":");
        jPanel1.add(staffIdLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 20, 20));

        staffIdLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel5.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel5.setText("Source Station             ");
        jPanel1.add(staffIdLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 220, 20));

        staffIdLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel6.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel6.setText("Destination Station      ");
        jPanel1.add(staffIdLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 220, 20));

        staffIdLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel7.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel7.setText("Total Cost of Ticket                  ");
        jPanel1.add(staffIdLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 220, 20));

        staffIdLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel8.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel8.setText("NULL");
        jPanel1.add(staffIdLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 280, 20));

        staffIdLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel9.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel9.setText("NULL");
        jPanel1.add(staffIdLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 280, 20));

        staffIdLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel10.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel10.setText("NULL");
        jPanel1.add(staffIdLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 280, 20));

        staffIdLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel11.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel11.setText("NULL");
        jPanel1.add(staffIdLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 280, 20));

        staffIdLabel12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel12.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel12.setText("NULL");
        jPanel1.add(staffIdLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 280, 20));

        cancelButton1.setBackground(new java.awt.Color(255, 255, 255));
        cancelButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButton1.setText("Cancel Ticket");
        cancelButton1.setFocusable(false);
        cancelButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, 170, 30));

        staffIdLabel13.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        staffIdLabel13.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel13.setText("Passenger(s) Information");
        jPanel1.add(staffIdLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 280, 30));

        staffIdLabel14.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel14.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel14.setText("NULL");
        jPanel1.add(staffIdLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 280, 20));

        staffIdLabel15.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel15.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel15.setText("NULL");
        jPanel1.add(staffIdLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 190, 20));

        staffIdLabel16.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel16.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel16.setText("NULL");
        jPanel1.add(staffIdLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 190, 20));

        staffIdLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel17.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel17.setText("Passenger Name");
        jPanel1.add(staffIdLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 150, 20));

        staffIdLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel18.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel18.setText("Date of Journey           ");
        jPanel1.add(staffIdLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 220, 20));

        staffIdLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel19.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel19.setText("Bus Timing                   ");
        jPanel1.add(staffIdLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 220, 20));

        staffIdLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel20.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel20.setText("Total Distance in Mile   ");
        jPanel1.add(staffIdLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 220, 20));

        staffIdLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel21.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel21.setText("Total Journey Time in Hour      ");
        jPanel1.add(staffIdLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 220, 20));

        staffIdLabel22.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel22.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel22.setText("NULL");
        jPanel1.add(staffIdLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 280, 20));

        staffIdLabel23.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel23.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel23.setText("NULL");
        jPanel1.add(staffIdLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 280, 20));

        staffIdLabel24.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel24.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel24.setText("NULL");
        jPanel1.add(staffIdLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 280, 20));

        staffIdLabel25.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel25.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel25.setText("NULL");
        jPanel1.add(staffIdLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 280, 20));

        staffIdLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel26.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel26.setText("PNR Number                ");
        jPanel1.add(staffIdLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, 20));

        staffIdLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel27.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel27.setText(":");
        jPanel1.add(staffIdLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 20, 20));

        staffIdLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel28.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel28.setText(":");
        jPanel1.add(staffIdLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 20, 20));

        staffIdLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel29.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel29.setText(":");
        jPanel1.add(staffIdLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 20, 20));

        staffIdLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel31.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel31.setText(":");
        jPanel1.add(staffIdLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 20, 20));

        staffIdLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel32.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel32.setText(":");
        jPanel1.add(staffIdLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 20, 20));

        staffIdLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel33.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel33.setText(":");
        jPanel1.add(staffIdLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 20, 20));

        staffIdLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel34.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel34.setText(":");
        jPanel1.add(staffIdLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 20, 20));

        staffIdLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel35.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel35.setText(":");
        jPanel1.add(staffIdLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 20, 20));

        staffIdLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel30.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel30.setText(":");
        jPanel1.add(staffIdLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 20, 20));
        jPanel1.add(staffNameSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 680, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PassengerTicket dialog = new PassengerTicket(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel staffIdLabel;
    private javax.swing.JLabel staffIdLabel1;
    private javax.swing.JLabel staffIdLabel10;
    private javax.swing.JLabel staffIdLabel11;
    private javax.swing.JLabel staffIdLabel12;
    private javax.swing.JLabel staffIdLabel13;
    private javax.swing.JLabel staffIdLabel14;
    private javax.swing.JLabel staffIdLabel15;
    private javax.swing.JLabel staffIdLabel16;
    private javax.swing.JLabel staffIdLabel17;
    private javax.swing.JLabel staffIdLabel18;
    private javax.swing.JLabel staffIdLabel19;
    private javax.swing.JLabel staffIdLabel2;
    private javax.swing.JLabel staffIdLabel20;
    private javax.swing.JLabel staffIdLabel21;
    private javax.swing.JLabel staffIdLabel22;
    private javax.swing.JLabel staffIdLabel23;
    private javax.swing.JLabel staffIdLabel24;
    private javax.swing.JLabel staffIdLabel25;
    private javax.swing.JLabel staffIdLabel26;
    private javax.swing.JLabel staffIdLabel27;
    private javax.swing.JLabel staffIdLabel28;
    private javax.swing.JLabel staffIdLabel29;
    private javax.swing.JLabel staffIdLabel3;
    private javax.swing.JLabel staffIdLabel30;
    private javax.swing.JLabel staffIdLabel31;
    private javax.swing.JLabel staffIdLabel32;
    private javax.swing.JLabel staffIdLabel33;
    private javax.swing.JLabel staffIdLabel34;
    private javax.swing.JLabel staffIdLabel35;
    private javax.swing.JLabel staffIdLabel4;
    private javax.swing.JLabel staffIdLabel5;
    private javax.swing.JLabel staffIdLabel6;
    private javax.swing.JLabel staffIdLabel7;
    private javax.swing.JLabel staffIdLabel8;
    private javax.swing.JLabel staffIdLabel9;
    private javax.swing.JLabel staffNameLabel1;
    private javax.swing.JSeparator staffNameSeparator;
    private javax.swing.JSeparator staffNameSeparator1;
    // End of variables declaration//GEN-END:variables
}
