/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busticket;

/**
 *
 * @author pravinewa
 */
public class ShowStaffDetail extends javax.swing.JDialog {

    /**
     * Creates new form ShowStaffDetail
     */
    public ShowStaffDetail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        staffNameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        contactNumberLabel = new javax.swing.JLabel();
        emailIDLabel = new javax.swing.JLabel();
        iRDLabel = new javax.swing.JLabel();
        shiftLabel = new javax.swing.JLabel();
        showStaffNameLabel = new javax.swing.JLabel();
        staffIdLabel = new javax.swing.JLabel();
        showGenderLabel = new javax.swing.JLabel();
        showAddressLabel = new javax.swing.JLabel();
        showContactNumberLabel = new javax.swing.JLabel();
        showEmailIDLabel = new javax.swing.JLabel();
        showIRDLabel = new javax.swing.JLabel();
        showShiftLabel = new javax.swing.JLabel();
        showStaffIDLabel = new javax.swing.JLabel();
        titleSeparator = new javax.swing.JSeparator();
        titleLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.9F);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 50, 67));
        jPanel1.setPreferredSize(new java.awt.Dimension(440, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staffNameLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        staffNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        staffNameLabel.setText("Staff Name : ");
        jPanel1.add(staffNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 20));

        genderLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText("Gender : ");
        jPanel1.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 80, 20));

        addressLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(255, 255, 255));
        addressLabel.setText("Address :");
        jPanel1.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 80, 20));

        contactNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        contactNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        contactNumberLabel.setText("Contact Number :");
        jPanel1.add(contactNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 140, 20));

        emailIDLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        emailIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailIDLabel.setText("Email ID : ");
        jPanel1.add(emailIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 80, 20));

        iRDLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        iRDLabel.setForeground(new java.awt.Color(255, 255, 255));
        iRDLabel.setText("ID Registered Date : ");
        jPanel1.add(iRDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 160, 20));

        shiftLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        shiftLabel.setForeground(new java.awt.Color(255, 255, 255));
        shiftLabel.setText("Shift : ");
        jPanel1.add(shiftLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 80, 20));

        showStaffNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showStaffNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        showStaffNameLabel.setText("NULL");
        jPanel1.add(showStaffNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 210, 20));

        staffIdLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        staffIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel.setText("Staff ID : ");
        jPanel1.add(staffIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 80, 20));

        showGenderLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showGenderLabel.setForeground(new java.awt.Color(255, 255, 255));
        showGenderLabel.setText("NULL");
        jPanel1.add(showGenderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 210, 20));

        showAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showAddressLabel.setForeground(new java.awt.Color(255, 255, 255));
        showAddressLabel.setText("NULL");
        jPanel1.add(showAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 210, 20));

        showContactNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showContactNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        showContactNumberLabel.setText("NULL");
        jPanel1.add(showContactNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 210, 20));

        showEmailIDLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showEmailIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        showEmailIDLabel.setText("NULL");
        jPanel1.add(showEmailIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 210, 20));

        showIRDLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showIRDLabel.setForeground(new java.awt.Color(255, 255, 255));
        showIRDLabel.setText("NULL");
        jPanel1.add(showIRDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 210, 20));

        showShiftLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showShiftLabel.setForeground(new java.awt.Color(255, 255, 255));
        showShiftLabel.setText("NULL");
        jPanel1.add(showShiftLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 210, 20));

        showStaffIDLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showStaffIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        showStaffIDLabel.setText("NULL");
        jPanel1.add(showStaffIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 210, 20));
        jPanel1.add(titleSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 400, 10));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Staff Details");
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, -1));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setBorderPainted(false);
        backButton.setFocusPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowStaffDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowStaffDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowStaffDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowStaffDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ShowStaffDetail dialog = new ShowStaffDetail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel contactNumberLabel;
    private javax.swing.JLabel emailIDLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel iRDLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel shiftLabel;
    private javax.swing.JLabel showAddressLabel;
    private javax.swing.JLabel showContactNumberLabel;
    private javax.swing.JLabel showEmailIDLabel;
    private javax.swing.JLabel showGenderLabel;
    private javax.swing.JLabel showIRDLabel;
    private javax.swing.JLabel showShiftLabel;
    private javax.swing.JLabel showStaffIDLabel;
    private javax.swing.JLabel showStaffNameLabel;
    private javax.swing.JLabel staffIdLabel;
    private javax.swing.JLabel staffNameLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JSeparator titleSeparator;
    // End of variables declaration//GEN-END:variables
}
