/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busticket;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author pravinewa
 */
public class TicketPrice extends javax.swing.JDialog {
    static int ivalid = 0, pvalid = 0, snvalid = 0, emailvalid = 0, contactnumbervalid = 0, addressvalid = 0;
    
    /**
     * Creates new form AddStaff
     */
    public TicketPrice(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        staffIdLabel3 = new javax.swing.JLabel();
        staffIdLabel7 = new javax.swing.JLabel();
        staffIdLabel8 = new javax.swing.JLabel();
        staffIdLabel9 = new javax.swing.JLabel();
        staffIdLabel13 = new javax.swing.JLabel();
        staffIdLabel30 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.9F);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 50, 67));
        jPanel1.setPreferredSize(new java.awt.Dimension(440, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staffIdLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel3.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel3.setText("PNR Number   ");
        jPanel1.add(staffIdLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, 20));

        staffIdLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel7.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel7.setText("Total Cost");
        jPanel1.add(staffIdLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 100, 20));

        staffIdLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel8.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel8.setText("NULL");
        jPanel1.add(staffIdLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 210, 20));

        staffIdLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        staffIdLabel9.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel9.setText("NULL");
        jPanel1.add(staffIdLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 210, 20));

        staffIdLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel13.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel13.setText(":");
        jPanel1.add(staffIdLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 20, 20));

        staffIdLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel30.setForeground(new java.awt.Color(255, 255, 255));
        staffIdLabel30.setText(":");
        jPanel1.add(staffIdLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 20, 20));

        addButton.setBackground(new java.awt.Color(255, 255, 255));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addButton.setText("OK");
        addButton.setFocusable(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/3ac514df5b4f36e2d8d525fe7f63b83c.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 190));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        PassengerTicket dialog = new PassengerTicket(new javax.swing.JFrame(), true);
        this.dispose();
        dialog.setVisible(true);
        
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TicketPrice dialog = new TicketPrice(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel staffIdLabel13;
    private javax.swing.JLabel staffIdLabel3;
    private javax.swing.JLabel staffIdLabel30;
    private javax.swing.JLabel staffIdLabel7;
    private javax.swing.JLabel staffIdLabel8;
    private javax.swing.JLabel staffIdLabel9;
    // End of variables declaration//GEN-END:variables
}
