/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busticket;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author pravinewa
 */
public class TicketDetails extends javax.swing.JFrame {
    static int sidebar = 0;
    static int mousepX, mousepY;  
    /**
     * Creates new form OpenPanel
     */
    public TicketDetails() {
        initComponents();
    }
    private void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();
        showButton = new javax.swing.JButton();
        lineSeparator3 = new javax.swing.JSeparator();
        lineSeparator2 = new javax.swing.JSeparator();
        lineSeparator1 = new javax.swing.JSeparator();
        lineSeparator4 = new javax.swing.JSeparator();
        lineSeparator5 = new javax.swing.JSeparator();
        signOutLabel = new javax.swing.JLabel();
        HideLabel = new javax.swing.JLabel();
        fareCalculatorLabel = new javax.swing.JLabel();
        busManagementLabel = new javax.swing.JLabel();
        lineSeparator6 = new javax.swing.JSeparator();
        reservationButton = new javax.swing.JButton();
        reservationLabel = new javax.swing.JLabel();
        adminButton = new javax.swing.JButton();
        lineSeparator7 = new javax.swing.JSeparator();
        adminPanelLabel = new javax.swing.JLabel();
        ticketButton = new javax.swing.JButton();
        lineSeparator8 = new javax.swing.JSeparator();
        ticketLabel = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        minimizeButton = new javax.swing.JButton();
        showUserLabel = new javax.swing.JLabel();
        showUserLabel1 = new javax.swing.JLabel();
        staffIdTextField = new javax.swing.JTextField();
        staffIdSeperator = new javax.swing.JSeparator();
        staffIdLabel1 = new javax.swing.JLabel();
        addButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        mainPanel.setPreferredSize(new java.awt.Dimension(1070, 530));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarPanel.setBackground(new java.awt.Color(1, 50, 67));

        addButton.setBackground(new java.awt.Color(1, 50, 67));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/icons8-calendar-416.png"))); // NOI18N
        addButton.setBorder(null);
        addButton.setBorderPainted(false);
        addButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addButton.setFocusPainted(false);
        addButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(1, 50, 67));
        searchButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/icons8-calculator-500.png"))); // NOI18N
        searchButton.setBorder(null);
        searchButton.setBorderPainted(false);
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.setFocusPainted(false);
        searchButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        signOutButton.setBackground(new java.awt.Color(1, 50, 67));
        signOutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signOutButton.setForeground(new java.awt.Color(255, 255, 255));
        signOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/sign-out.png"))); // NOI18N
        signOutButton.setBorder(null);
        signOutButton.setBorderPainted(false);
        signOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOutButton.setFocusPainted(false);
        signOutButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });

        showButton.setBackground(new java.awt.Color(1, 50, 67));
        showButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showButton.setForeground(new java.awt.Color(255, 255, 255));
        showButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/menu.png"))); // NOI18N
        showButton.setBorder(null);
        showButton.setBorderPainted(false);
        showButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showButton.setFocusPainted(false);
        showButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        signOutLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signOutLabel.setForeground(new java.awt.Color(255, 255, 255));
        signOutLabel.setText("Sign Out");
        signOutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signOutLabelMouseClicked(evt);
            }
        });

        HideLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HideLabel.setForeground(new java.awt.Color(255, 255, 255));
        HideLabel.setText("Hide");
        HideLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HideLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HideLabelMouseClicked(evt);
            }
        });

        fareCalculatorLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fareCalculatorLabel.setForeground(new java.awt.Color(255, 255, 255));
        fareCalculatorLabel.setText("Fare Calculator");
        fareCalculatorLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fareCalculatorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fareCalculatorLabelMouseClicked(evt);
            }
        });

        busManagementLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        busManagementLabel.setForeground(new java.awt.Color(255, 255, 255));
        busManagementLabel.setText("Bus Management");
        busManagementLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        busManagementLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busManagementLabelMouseClicked(evt);
            }
        });

        reservationButton.setBackground(new java.awt.Color(1, 50, 67));
        reservationButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reservationButton.setForeground(new java.awt.Color(255, 255, 255));
        reservationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/icons8-new-ticket-416.png"))); // NOI18N
        reservationButton.setBorder(null);
        reservationButton.setBorderPainted(false);
        reservationButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reservationButton.setFocusPainted(false);
        reservationButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        reservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationButtonActionPerformed(evt);
            }
        });

        reservationLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reservationLabel.setForeground(new java.awt.Color(255, 255, 255));
        reservationLabel.setText("Reservation");
        reservationLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reservationLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationLabelMouseClicked(evt);
            }
        });

        adminButton.setBackground(new java.awt.Color(1, 50, 67));
        adminButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adminButton.setForeground(new java.awt.Color(255, 255, 255));
        adminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/settings.png"))); // NOI18N
        adminButton.setBorder(null);
        adminButton.setBorderPainted(false);
        adminButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminButton.setFocusPainted(false);
        adminButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        adminPanelLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adminPanelLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminPanelLabel.setText("Account Setting");
        adminPanelLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminPanelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanelLabelMouseClicked(evt);
            }
        });

        ticketButton.setBackground(new java.awt.Color(1, 50, 67));
        ticketButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ticketButton.setForeground(new java.awt.Color(255, 255, 255));
        ticketButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/icons8-ticket-416.png"))); // NOI18N
        ticketButton.setBorder(null);
        ticketButton.setBorderPainted(false);
        ticketButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ticketButton.setFocusPainted(false);
        ticketButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ticketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketButtonActionPerformed(evt);
            }
        });

        ticketLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ticketLabel.setForeground(new java.awt.Color(255, 255, 255));
        ticketLabel.setText("Tickets");
        ticketLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ticketLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticketLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lineSeparator4)
            .addComponent(lineSeparator5)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lineSeparator3)
                    .addComponent(lineSeparator2)
                    .addComponent(lineSeparator1)
                    .addComponent(lineSeparator6)
                    .addComponent(lineSeparator7)
                    .addComponent(lineSeparator8)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fareCalculatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(showButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HideLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(signOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(signOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(busManagementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(reservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reservationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adminPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(ticketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ticketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(showButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HideLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(lineSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busManagementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fareCalculatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(adminPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addComponent(ticketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ticketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(lineSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addComponent(signOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(signOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        mainPanel.add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 40, 650));

        titlePanel.setBackground(new java.awt.Color(0, 0, 0));
        titlePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlePanelMouseDragged(evt);
            }
        });
        titlePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlePanelMousePressed(evt);
            }
        });

        closeButton.setBackground(new java.awt.Color(0, 0, 0));
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/close-window.png"))); // NOI18N
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.setFocusable(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        minimizeButton.setBackground(new java.awt.Color(0, 0, 0));
        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/minimize-window-filled.png"))); // NOI18N
        minimizeButton.setBorderPainted(false);
        minimizeButton.setContentAreaFilled(false);
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.setFocusable(false);
        minimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeButtonActionPerformed(evt);
            }
        });

        showUserLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        showUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        showUserLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/user.png"))); // NOI18N
        showUserLabel.setText("User");
        showUserLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showUserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showUserLabelMouseClicked(evt);
            }
        });

        showUserLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        showUserLabel1.setForeground(new java.awt.Color(255, 255, 255));
        showUserLabel1.setText("Logged in at : ");
        showUserLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(showUserLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296)
                .addComponent(showUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 406, Short.MAX_VALUE)
                .addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(showUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(showUserLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(minimizeButton)
                    .addComponent(closeButton)))
        );

        mainPanel.add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 30));

        staffIdTextField.setBorder(null);
        staffIdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                staffIdTextFieldKeyReleased(evt);
            }
        });
        mainPanel.add(staffIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 200, 40));
        mainPanel.add(staffIdSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 200, 10));

        staffIdLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffIdLabel1.setText("Enter PNR Number of Ticket");
        mainPanel.add(staffIdLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 200, 20));

        addButton1.setBackground(new java.awt.Color(255, 255, 255));
        addButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addButton1.setText("Get Ticket Details");
        addButton1.setFocusable(false);
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });
        mainPanel.add(addButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 160, 40));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        switch(sidebar)
        {
            case 0:
            {
                sidebarPanel.setSize(220,650);
                showButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/hide.png"))); // NOI18N


                //------------------------------------------------------//
                sidebar = 1;
                break;
            }
            case 1:
            {
                sidebarPanel.setSize(40,650);
                showButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/menu.png"))); // NOI18N
                sidebar = 0;
                break;
            }
        }
        System.out.println(sidebar);
           
    }//GEN-LAST:event_showButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        BusManagement bm = new BusManagement();
        bm.setVisible(true);
        close();
    }//GEN-LAST:event_addButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        FareCalculator fc = new FareCalculator();
        fc.setVisible(true);
        close();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
//        DeleteDialog dialog = new DeleteDialog(new javax.swing.JFrame(), true);
//        dialog.setVisible(true);
    }//GEN-LAST:event_signOutButtonActionPerformed

    private void signOutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutLabelMouseClicked
        System.out.println("adasd");
    }//GEN-LAST:event_signOutLabelMouseClicked

    private void HideLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HideLabelMouseClicked
        switch(sidebar)
        {
            case 0:
            {
                sidebarPanel.setSize(220,650);
                showButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/hide.png"))); // NOI18N


                //------------------------------------------------------//
                sidebar = 1;
                break;
            }
            case 1:
            {
                sidebarPanel.setSize(40,650);
                showButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticket/icons/menu.png"))); // NOI18N
                sidebar = 0;
                break;
            }
        }
        
    }//GEN-LAST:event_HideLabelMouseClicked

    private void fareCalculatorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fareCalculatorLabelMouseClicked
        FareCalculator fc = new FareCalculator();
        fc.setVisible(true);
        close();
    }//GEN-LAST:event_fareCalculatorLabelMouseClicked

    private void busManagementLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busManagementLabelMouseClicked
        BusManagement bm = new BusManagement();
        bm.setVisible(true);
        close();
    }//GEN-LAST:event_busManagementLabelMouseClicked

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        close();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void minimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeButtonActionPerformed
        this.setState(TicketDetails.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonActionPerformed

    private void titlePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePanelMouseDragged
        int kordinateX = evt.getXOnScreen();
        int kordinateY = evt.getYOnScreen();
        
        this.setLocation(kordinateX-mousepX, kordinateY-mousepY);
    }//GEN-LAST:event_titlePanelMouseDragged

    private void titlePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePanelMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
        
    }//GEN-LAST:event_titlePanelMousePressed

    private void showUserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showUserLabelMouseClicked
        ShowStaffDetail dialog = new ShowStaffDetail(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_showUserLabelMouseClicked

    private void reservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationButtonActionPerformed
        NewTicketPanel ntp = new NewTicketPanel();
        ntp.setVisible(true);
        close();
    }//GEN-LAST:event_reservationButtonActionPerformed

    private void reservationLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationLabelMouseClicked
        NewTicketPanel ntp = new NewTicketPanel();
        ntp.setVisible(true);
        close();
    }//GEN-LAST:event_reservationLabelMouseClicked

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        AccountSetting as = new AccountSetting();
        as.setVisible(true);
        close();
    }//GEN-LAST:event_adminButtonActionPerformed

    private void adminPanelLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelLabelMouseClicked
        AccountSetting as = new AccountSetting();
        as.setVisible(true);
        close();
    }//GEN-LAST:event_adminPanelLabelMouseClicked

    private void ticketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketButtonActionPerformed

    private void ticketLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketLabelMouseClicked

    private void staffIdTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_staffIdTextFieldKeyReleased

    }//GEN-LAST:event_staffIdTextFieldKeyReleased

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        PassengerTicket dialog = new PassengerTicket(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_addButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HideLabel;
    private javax.swing.JButton addButton;
    public javax.swing.JButton addButton1;
    private javax.swing.JButton adminButton;
    private javax.swing.JLabel adminPanelLabel;
    private javax.swing.JLabel busManagementLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel fareCalculatorLabel;
    private javax.swing.JSeparator lineSeparator1;
    private javax.swing.JSeparator lineSeparator2;
    private javax.swing.JSeparator lineSeparator3;
    private javax.swing.JSeparator lineSeparator4;
    private javax.swing.JSeparator lineSeparator5;
    private javax.swing.JSeparator lineSeparator6;
    private javax.swing.JSeparator lineSeparator7;
    private javax.swing.JSeparator lineSeparator8;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton minimizeButton;
    private javax.swing.JButton reservationButton;
    private javax.swing.JLabel reservationLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton showButton;
    private javax.swing.JLabel showUserLabel;
    private javax.swing.JLabel showUserLabel1;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JButton signOutButton;
    private javax.swing.JLabel signOutLabel;
    private javax.swing.JLabel staffIdLabel1;
    private javax.swing.JSeparator staffIdSeperator;
    private javax.swing.JTextField staffIdTextField;
    private javax.swing.JButton ticketButton;
    private javax.swing.JLabel ticketLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
